OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - 127.0.0.1
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - 127.0.0.1
    Users:
      Count: 1

  # - Name: Org2
  #   Domain: org2.example.com
  #   EnableNodeOUs: true
  #   Template:
  #     Template:
  #     Count: 1
  #     SANS:
  #       - 127.0.0.1
  #   Users:
  #     Count: 1
